import Config


port = get_env("PORT", 5000, :int)
host = get_env("HOST", "localhost")
host_port = get_env("HOST_PORT", 5000, :int)
url_scheme = if host_port == 443, do: "https", else: "http"

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :time_manager, TimeManagerWeb.Endpoint,
  http: [port: port],
  url: [
    host: host,
    port: host_port,
    scheme: url_scheme
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: TimeManager.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
